//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidiForwarder.Resources {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MidiForwarder.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 一个简单的MIDI信号转发工具，
        ///用于将MIDI输入设备信号转发到输出设备。.
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        internal static string AboutOkButton {
            get {
                return ResourceManager.GetString("AboutOkButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIDI信号转发器.
        /// </summary>
        internal static string AboutSoftwareName {
            get {
                return ResourceManager.GetString("AboutSoftwareName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 版本: {0}.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIDI Forwarder.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启动时自动连接.
        /// </summary>
        internal static string AutoConnectOnStartup {
            get {
                return ResourceManager.GetString("AutoConnectOnStartup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 点击【是】最小化到托盘，点击【否】直接退出程序。
        ///
        ///您可以通过托盘菜单更改此设置。.
        /// </summary>
        internal static string CloseConfirmMessage {
            get {
                return ResourceManager.GetString("CloseConfirmMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关闭确认.
        /// </summary>
        internal static string CloseConfirmTitle {
            get {
                return ResourceManager.GetString("CloseConfirmTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIDI输入设备.
        /// </summary>
        internal static string InputDeviceGroup {
            get {
                return ResourceManager.GetString("InputDeviceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [{0:HH:mm:ss.fff}] {1} - 通道: {2}, 数据1: {3}, 数据2: {4}.
        /// </summary>
        internal static string LogMessageFormat {
            get {
                return ResourceManager.GetString("LogMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIDI消息日志.
        /// </summary>
        internal static string LogGroup {
            get {
                return ResourceManager.GetString("LogGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 开机自启动已禁用.
        /// </summary>
        internal static string MsgAutoStartDisabled {
            get {
                return ResourceManager.GetString("MsgAutoStartDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 开机自启动已启用.
        /// </summary>
        internal static string MsgAutoStartEnabled {
            get {
                return ResourceManager.GetString("MsgAutoStartEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已连接设备.
        /// </summary>
        internal static string MsgConnected {
            get {
                return ResourceManager.GetString("MsgConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设备已断开连接.
        /// </summary>
        internal static string MsgDisconnected {
            get {
                return ResourceManager.GetString("MsgDisconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设备选择已更改，连接已断开.
        /// </summary>
        internal static string MsgDisconnectedDueToDeviceChange {
            get {
                return ResourceManager.GetString("MsgDisconnectedDueToDeviceChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设备列表已刷新.
        /// </summary>
        internal static string MsgDevicesRefreshed {
            get {
                return ResourceManager.GetString("MsgDevicesRefreshed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIDI输出设备.
        /// </summary>
        internal static string OutputDeviceGroup {
            get {
                return ResourceManager.GetString("OutputDeviceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 刷新设备列表.
        /// </summary>
        internal static string RefreshDevicesButton {
            get {
                return ResourceManager.GetString("RefreshDevicesButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择输入设备：.
        /// </summary>
        internal static string SelectInputDevice {
            get {
                return ResourceManager.GetString("SelectInputDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择输出设备：.
        /// </summary>
        internal static string SelectOutputDevice {
            get {
                return ResourceManager.GetString("SelectOutputDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 状态：已连接.
        /// </summary>
        internal static string StatusConnected {
            get {
                return ResourceManager.GetString("StatusConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 状态：未连接.
        /// </summary>
        internal static string StatusDisconnected {
            get {
                return ResourceManager.GetString("StatusDisconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 连接设备.
        /// </summary>
        internal static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 断开连接.
        /// </summary>
        internal static string DisconnectButton {
            get {
                return ResourceManager.GetString("DisconnectButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string TrayAbout {
            get {
                return ResourceManager.GetString("TrayAbout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 开机自启动.
        /// </summary>
        internal static string TrayAutoBoot {
            get {
                return ResourceManager.GetString("TrayAutoBoot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 程序已最小化到托盘.
        /// </summary>
        internal static string TrayBalloonText {
            get {
                return ResourceManager.GetString("TrayBalloonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIDI信号转发器.
        /// </summary>
        internal static string TrayBalloonTitle {
            get {
                return ResourceManager.GetString("TrayBalloonTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string TrayLanguage {
            get {
                return ResourceManager.GetString("TrayLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        internal static string TrayLanguageChinese {
            get {
                return ResourceManager.GetString("TrayLanguageChinese", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string TrayLanguageEnglish {
            get {
                return ResourceManager.GetString("TrayLanguageEnglish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        internal static string TrayLanguageSystem {
            get {
                return ResourceManager.GetString("TrayLanguageSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 最小化到托盘.
        /// </summary>
        internal static string TrayMinimizeToTray {
            get {
                return ResourceManager.GetString("TrayMinimizeToTray", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIDI信号转发器.
        /// </summary>
        internal static string TrayTooltip {
            get {
                return ResourceManager.GetString("TrayTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 添加到蓝牙过滤排除名单.
        /// </summary>
        internal static string AddToExclusionList {
            get {
                return ResourceManager.GetString("AddToExclusionList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 从蓝牙过滤排除名单中移除.
        /// </summary>
        internal static string RemoveFromExclusionList {
            get {
                return ResourceManager.GetString("RemoveFromExclusionList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已将 &apos;{0}&apos; 添加到蓝牙过滤排除名单.
        /// </summary>
        internal static string LogAddedToExclusionList {
            get {
                return ResourceManager.GetString("LogAddedToExclusionList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已将 &apos;{0}&apos; 从蓝牙过滤排除名单中移除.
        /// </summary>
        internal static string LogRemovedFromExclusionList {
            get {
                return ResourceManager.GetString("LogRemovedFromExclusionList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 该设备将不再被识别为蓝牙设备.
        /// </summary>
        internal static string LogDeviceWillNotBeBluetooth {
            get {
                return ResourceManager.GetString("LogDeviceWillNotBeBluetooth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 该设备将恢复蓝牙设备检测.
        /// </summary>
        internal static string LogDeviceWillResumeBluetooth {
            get {
                return ResourceManager.GetString("LogDeviceWillResumeBluetooth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 检测到蓝牙MIDI设备.
        /// </summary>
        internal static string LogBluetoothMidiDetected {
            get {
                return ResourceManager.GetString("LogBluetoothMidiDetected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 注意：蓝牙设备可能出现驱动状态与实际连接状态不同步的情况.
        /// </summary>
        internal static string LogBluetoothNote {
            get {
                return ResourceManager.GetString("LogBluetoothNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 如果无法收发MIDI消息，请尝试：.
        /// </summary>
        internal static string LogBluetoothTryIfFail {
            get {
                return ResourceManager.GetString("LogBluetoothTryIfFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1. 检查蓝牙设备是否真正连接.
        /// </summary>
        internal static string LogBluetoothTry1 {
            get {
                return ResourceManager.GetString("LogBluetoothTry1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2. 断开并重新连接设备.
        /// </summary>
        internal static string LogBluetoothTry2 {
            get {
                return ResourceManager.GetString("LogBluetoothTry2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 3. 重启蓝牙设备或重新配对.
        /// </summary>
        internal static string LogBluetoothTry3 {
            get {
                return ResourceManager.GetString("LogBluetoothTry3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 检测到的蓝牙输入设备: {0}.
        /// </summary>
        internal static string LogDetectedBluetoothInput {
            get {
                return ResourceManager.GetString("LogDetectedBluetoothInput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 检测到的蓝牙输出设备: {0}.
        /// </summary>
        internal static string LogDetectedBluetoothOutput {
            get {
                return ResourceManager.GetString("LogDetectedBluetoothOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 请先选择一个输入设备.
        /// </summary>
        internal static string LogSelectInputFirst {
            get {
                return ResourceManager.GetString("LogSelectInputFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 请先选择一个输出设备.
        /// </summary>
        internal static string LogSelectOutputFirst {
            get {
                return ResourceManager.GetString("LogSelectOutputFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动连接失败，未找到保存的设备：输入=&apos;{0}&apos;, 输出=&apos;{1}&apos;.
        /// </summary>
        internal static string LogAutoConnectFailed {
            get {
                return ResourceManager.GetString("LogAutoConnectFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 将在 {0} 秒后进行第 1 次重试....
        /// </summary>
        internal static string LogAutoConnectRetryIn {
            get {
                return ResourceManager.GetString("LogAutoConnectRetryIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 用户已操作界面，自动连接重试已取消.
        /// </summary>
        internal static string LogAutoConnectCancelled {
            get {
                return ResourceManager.GetString("LogAutoConnectCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动连接失败，已重试 {0} 次，请手动连接设备.
        /// </summary>
        internal static string LogAutoConnectFailedAfterRetries {
            get {
                return ResourceManager.GetString("LogAutoConnectFailedAfterRetries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 第 {0} 次重试失败，将在 {1} 秒后进行第 {2} 次重试....
        /// </summary>
        internal static string LogAutoConnectRetryFailed {
            get {
                return ResourceManager.GetString("LogAutoConnectRetryFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法找到设备ID: 输入设备=&apos;{0}&apos;, 输出设备=&apos;{1}&apos;.
        /// </summary>
        internal static string LogDeviceNotFound {
            get {
                return ResourceManager.GetString("LogDeviceNotFound", resourceCulture);
            }
        }
    }
}
